IF OBJECT_ID (N'FT_GET_DEPARTMENTS') IS NOT NULL  
    DROP FUNCTION FT_GET_DEPARTMENTS;  
GO
create FUNCTION FT_GET_DEPARTMENTS()
RETURNS TABLE
AS
RETURN
SELECT
    idDepartments as id,
    [name]
FROM
    TBL_DEPARTMENTS
GO