IF OBJECT_ID (N'FT_GET_REQUEST_TYPE', N'IF') IS NOT NULL
    DROP FUNCTION [FT_GET_REQUEST_TYPE];
GO
CREATE FUNCTION [FT_GET_DELIVERY_TYPE] ()
RETURNS TABLE
AS  
RETURN(
    SELECT  idDeliveryType as id,
            name as name
    FROM [pyflor].[dbo].[TBL_DELIVERY_TYPES]
)
