//Acciones de los productos
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ADD_QUANTITY_PRODUCT = 'ADD_QUANTITY_PRODUCT';
export const SUBSTRACT_QUANTITY_PRODUCT = 'SUBSTRACT_QUANTITY_PRODUCT';